#!/usr/bin/env python3
"""Render the generated README sections from checked-in data.

Two README regions are generated and must never be edited by hand:

* ``stackage-coverage`` summarises ``data/baselines/*.json``, the reviewed
  Stackage comparison results asserted by ``nix flake check``.
* ``directive-tests`` counts, for every upstream hsc2hs directive, the fixture
  files and assertions that exercise it.

``--check`` fails when README.md differs from the rendered text (this is what
the unit tests run). ``--write`` rewrites the regions in place. ``--import``
copies fresh ``summary.json`` reports into ``data/baselines/`` first; the file
name selects the baseline, e.g. ``aarch64-linux-native.json``. Importing never
happens inside a Nix check: a changed baseline is reviewed as a pull request.
"""
import argparse
import json
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
README = ROOT / 'README.md'
BASELINES = ROOT / 'data/baselines'
MANIFEST = ROOT / 'data/stackage.json'
FIXTURES = ROOT / 'tests/mvp'
ASSERTION_SOURCES = [ROOT / 'test/Main.hs', ROOT / 'tests/mvp.py']
NOTICE = '<!-- Generated by tools/readme-stats.py; do not edit by hand. -->'

# Every directive documented by upstream hsc2hs, in documentation order.
# The status column is the candidate's implementation status, kept next to
# the implementation in src/Hsc2hs.hs.
DIRECTIVES = [
    ('include', 'supported'), ('define', 'supported'), ('undef', 'supported'),
    ('if', 'supported'), ('ifdef', 'supported'), ('ifndef', 'supported'),
    ('elif', 'supported'), ('else', 'supported'), ('endif', 'supported'),
    ('error', 'supported'), ('warning', 'supported'),
    ('const', 'supported'), ('const_str', 'supported'),
    ('type', 'supported'), ('peek', 'supported'), ('poke', 'supported'),
    ('ptr', 'supported'), ('offset', 'supported'), ('size', 'supported'),
    ('alignment', 'supported'), ('enum', 'supported'),
    ('let', 'unsupported'), ('def', 'unsupported'),
]
HOSTS = {'aarch64-linux': 'ARM64 Linux', 'x86_64-linux': 'x86-64 Linux',
         'aarch64-darwin': 'ARM64 macOS', 'x86_64-darwin': 'x86-64 macOS'}
ARCHES = {'aarch64': 'ARM64', 'arm64': 'ARM64', 'x86_64': 'x86-64', 'wasm32': 'Wasm32'}
OSES = {'linux': 'Linux', 'darwin': 'macOS', 'windows': 'Windows', 'wasi': 'WASI'}
HARD_ERRORS = ('setup_failures', 'tool_errors', 'reference_native_failures')


def target_name(triple):
    parts = triple.split('-')
    arch = ARCHES.get(parts[0], parts[0])
    os_name = next((OSES[o] for o in OSES if any(o in p for p in parts[1:])), parts[-1])
    return arch + ' ' + os_name


def stackage_rows():
    rows = []
    for path in sorted(BASELINES.glob('*.json')):
        host, mode = path.stem.rsplit('-', 1)
        baseline = json.loads(path.read_text())
        for cell, counts in baseline['by_target_mode'].items():
            triple, cell_mode = cell.rsplit('/', 1)
            if cell_mode != mode:
                raise ValueError(f'{path.name}: cell {cell} does not match the file mode')
            label = HOSTS.get(host, host)
            if mode == 'cross':
                label += ' → ' + target_name(triple)
            inapplicable = sum(1 for entry in baseline['inapplicable']
                               if entry['target'] == triple and entry['mode'] == mode)
            matches = sum(1 for case in baseline['verified_match_ids']
                          if case.endswith('/' + mode))
            rows.append({'label': label + ', ' + mode, 'matches': matches,
                         'applicable': counts['cases'], 'inapplicable': inapplicable,
                         'candidate_failures': counts['candidate_failures'],
                         'divergences': counts['divergences'],
                         'upstream_failures': counts['reference_cross_failures']})
    return sorted(rows, key=lambda row: (row['label'].endswith('cross'), row['label']))


def render_stackage():
    manifest = json.loads(MANIFEST.read_text())
    rows = stackage_rows()
    lines = [NOTICE, '',
             f"Snapshot: Stackage **{manifest['snapshot']}** ({manifest['compiler']}), "
             f"**{manifest['file_count']} `.hsc` files** in {manifest['packages_with_hsc']} packages, "
             f'discovered by unpacking all {manifest["package_count"]:,} package archives.', '',
             '| Host and mode | Byte-exact matches | Match rate | Candidate failures | Divergences | Upstream cross failures | Inapplicable |',
             '| --- | ---: | ---: | ---: | ---: | ---: | ---: |']
    for row in rows:
        rate = 100.0 * row['matches'] / row['applicable'] if row['applicable'] else 0.0
        total = row['applicable'] + row['inapplicable']
        if total != manifest['file_count']:
            raise ValueError(f"{row['label']}: {total} files accounted for, expected {manifest['file_count']}")
        lines.append(f"| {row['label']} | {row['matches']} / {row['applicable']} | **{rate:.1f}%** "
                     f"| {row['candidate_failures']} | {row['divergences']} "
                     f"| {row['upstream_failures']} | {row['inapplicable']} |")
    return '\n'.join(lines)


def count_directives(text):
    counts = {name: 0 for name, _ in DIRECTIVES}
    for match in re.finditer(r'(?<!#)#\{?\s*([A-Za-z_]\w*)', text):
        if match.group(1) in counts:
            counts[match.group(1)] += 1
    # test/Main.hs feature assertions are written as ("directive args", ...).
    for match in re.finditer(r'\("([A-Za-z_]\w*) ', text):
        if match.group(1) in counts:
            counts[match.group(1)] += 1
    return counts


def directive_rows():
    fixtures = {path.name: path.read_text(encoding='utf-8', errors='replace')
                for path in sorted(FIXTURES.glob('*.hsc'))}
    per_fixture = {name: count_directives(text) for name, text in fixtures.items()}
    assertions = count_directives('\n'.join(p.read_text() for p in ASSERTION_SOURCES))
    rows = []
    for name, status in DIRECTIVES:
        files = sum(1 for counts in per_fixture.values() if counts[name])
        uses = sum(counts[name] for counts in per_fixture.values())
        rows.append({'name': name, 'status': status, 'files': files, 'uses': uses,
                     'assertions': assertions[name]})
    return rows, len(fixtures)


def render_directives():
    rows, fixture_count = directive_rows()
    lines = [NOTICE, '',
             f'Counted over the {fixture_count} fixture files in `tests/mvp/`, the Haskell unit '
             'suite in `test/Main.hs` and the CLI assertions in `tests/mvp.py`.', '',
             '| Directive | Status | Fixture files | Fixture uses | Unit and CLI assertions |',
             '| --- | --- | ---: | ---: | ---: |']
    for row in rows:
        lines.append(f"| `#{row['name']}` | {row['status']} | {row['files']} | {row['uses']} | {row['assertions']} |")
    return '\n'.join(lines)


SECTIONS = {'stackage-coverage': render_stackage, 'directive-tests': render_directives}


def render(readme):
    for name, renderer in SECTIONS.items():
        start, end = f'<!-- {name}:start -->', f'<!-- {name}:end -->'
        pattern = re.compile(re.escape(start) + r'.*?' + re.escape(end), re.DOTALL)
        if len(pattern.findall(readme)) != 1:
            raise ValueError(f'README.md must contain exactly one {name} region')
        readme = pattern.sub(lambda _: start + '\n' + renderer() + '\n' + end, readme)
    return readme


def import_summary(path):
    summary = json.loads(path.read_text())
    if not {'counts', 'by_target_mode', 'inapplicable', 'verified_match_ids'} <= set(summary):
        raise ValueError(f'{path}: not a corpus comparison summary')
    hard = {key: summary['counts'][key] for key in HARD_ERRORS if summary['counts'][key]}
    if hard:
        raise ValueError(f'{path}: refusing to import a report with hard errors {hard}')
    target = BASELINES / path.name
    if not re.fullmatch(r'[a-z0-9_]+-[a-z]+-(native|cross)\.json', path.name):
        raise ValueError(f'{path}: name must be <system>-<mode>.json')
    shutil.copyfile(path, target)
    return target


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument('--check', action='store_true', help='fail if README.md is out of date')
    action.add_argument('--write', action='store_true', help='rewrite the generated README regions')
    parser.add_argument('--import', dest='imports', type=Path, action='append', default=[],
                        metavar='SUMMARY_JSON', help='copy a summary.json into data/baselines/ first')
    args = parser.parse_args()
    for path in args.imports:
        print('imported', import_summary(path).relative_to(ROOT))
    current = README.read_text()
    rendered = render(current)
    if args.write:
        if rendered != current:
            README.write_text(rendered)
            print('updated README.md')
        else:
            print('README.md already up to date')
    elif rendered != current:
        sys.exit('README.md is out of date; run tools/readme-stats.py --write')


if __name__ == '__main__':
    main()
